project_id = "haypiczkunyffeeieoca"

[functions.sql-execute]
verify_jwt = false

[functions.cleanup-inactive]
verify_jwt = false

[functions.auth-send-otp]
verify_jwt = false

[functions.auth-verify-otp]
verify_jwt = false

[functions.auth-complete-signup]
verify_jwt = false

[functions.auth-complete-recovery]
verify_jwt = false
